trigger: none

pool:
  vmImage: ubuntu-latest

name: $(Date:yyyyMMdd).$(Rev:r) ${{ parameters.stringWithoutValues }}

parameters:
- name: stringWithoutValues
  type: string
  default: silviu
- name: stringWithValues
  type: string  
  default: value1
  values:
  - value1
  - value2

variables:
  varFromStringWithhoutValues: ${{ parameters.stringWithoutValues}}
  varWithFormatTemplate: ${{ format('Hello {0} {1}', parameters.stringWithoutValues, parameters.stringWithValues )}}
  varWithFormatRuntime: $[ format('Hello {0} {1}', '${{parameters.stringWithoutValues}}', '${{parameters.stringWithValues}}' ) ]


steps:
- script: echo ${{parameters.stringWithoutValues}}
  displayName: parameters.stringWithoutValues
- script: echo ${{parameters.stringWithValues}}
  displayName: parameters.stringWithValues
- script: echo ${{variables.varFromStringWithhoutValues}}
  displayName: variables.varFromStringWithhoutValues
- script: echo $(varFromStringWithhoutValues)
  displayName: varFromStringWithhoutValues
- script: echo $(varWithFormatTemplate)
  displayName: varWithFormatTemplate
- script: echo $(varWithFormatRuntime)
  displayName: varWithFormatRuntime    
- script: echo $(Build.BuildNumber)
  displayName: Build.BuildNumber   
- script: echo $(Build.SourceVersionMessage)
  displayName: Build.SourceVersionMessage   
