trigger: none

parameters:
- name: name
  type: string
  default: Silviu

extends:
  template: extends-template.yml
  parameters:
    name: ${{ parameters.name }}
    stages: 
    - template: include-template.yml
      parameters:
        name: ${{ parameters.name }}
