trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: stringWithoutValues
  type: string
  default: silviu
- name: stringWithValues
  type: string  
  default: value1
  values:
  - value1
  - value2

steps:
- script: echo ${{parameters.stringWithoutValues}}
  displayName: String without values
- script: echo ${{parameters.stringWithValues}}
  displayName: String with values