trigger: none

pool:
  vmImage: ubuntu-latest

parameters:
- name: stringWithoutValues
  type: string
  default: silviu
- name: stringWithValues
  type: string  
  default: value1
  values:
  - value1
  - value2

variables:
  varFromStringWithhoutValues: ${{ parameters.stringWithoutValues}}

steps:
- script: echo ${{parameters.stringWithoutValues}}
  displayName: parameters.stringWithoutValues
- script: echo ${{parameters.stringWithValues}}
  displayName: parameters.stringWithValues
- script: echo ${{variables.varFromStringWithhoutValues}}
  displayName: variables.varFromStringWithhoutValues
- script: echo $(varFromStringWithhoutValues)
  displayName: varFromStringWithhoutValues